# Generated by Django 5.2.7 on 2025-10-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True)),
                ('owner_name', models.CharField(blank=True, max_length=100)),
                ('is_allowed', models.BooleanField(default=True)),
            ],
        ),
    ]
