# Generated by Django 5.2.7 on 2025-10-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_allowedentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(blank=True, null=True)),
                ('uid', models.CharField(max_length=64)),
                ('owner_name', models.CharField(blank=True, max_length=100)),
                ('original_is_allowed', models.BooleanField(default=True)),
                ('reader', models.IntegerField()),
                ('exited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
